

SET DEFINE OFF;
SET SERVEROUTPUT ON

BEGIN

	--------PURGE  
	DELETE FROM LKGROEXOBJDROIT WHERE OBJID IN (SELECT OBJID FROM TEXOBJECT WHERE CODEOBJECT ='GET_LOCALPARTYIDENTIFIER');
	DELETE FROM TEXTREE WHERE OBJID IN (SELECT OBJID FROM TEXOBJECT WHERE CODEOBJECT ='GET_LOCALPARTYIDENTIFIER');
	DELETE FROM TEXOBJECT WHERE CODEOBJECT ='GET_LOCALPARTYIDENTIFIER';
	
	--------------------Objet1--------------
	----------------------------------------

    INSERT INTO TEXOBJECT (OBJID,CODEOBJECT,LABEL) SELECT SEQ_OBJID.NEXTVAL ,'GET_LOCALPARTYIDENTIFIER',
   'Retourne l''actcode pour le role emprunteur' FROM DUAL WHERE NOT EXISTS ( SELECT 1 FROM TEXOBJECT  WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER');

	-- Habilitation pour le endpoint
	  --------------------------------------------------------------------------------
INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'CPTEXP' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='CPTEXP');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUP9' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUP9');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE1' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE1');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE2' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE2');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE3' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE3');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE4' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE4');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE5' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE5');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE6' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE6');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GROUPE8' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GROUPE8');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPCTX' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPCTX');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPCTX1' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPCTX1');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPCTX2' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPCTX2');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPCTX3' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPCTX3');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPEEG' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPEEG');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPEEGV' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPEEGV');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPEMOP' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPEMOP');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPMEP' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPMEP');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPRCV' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPRCV');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPSAS' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPSAS');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'GRPVIEW' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='GRPVIEW');

INSERT INTO LKGROEXOBJDROIT (OBJID, GROCODE) SELECT t.OBJID, 'RSPGEST' 
FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
AND NOT EXISTS (SELECT 1 FROM LKGROEXOBJDROIT ld WHERE ld.OBJID = t.OBJID AND ld.GROCODE='RSPGEST');

----------------------------------------------------------------------------
	INSERT INTO TEXTREE (OBJID,NODE,NODEPARENT,SEARCHTYPE,SEARCHQUERY,HIDDENFIELD) 
	SELECT t.OBJID, 'GET_LOCALPARTYIDENTIFIER','GET_LOCALPARTYIDENTIFIER', 'REQ',
	'SELECT ACTCODE FROM ACTEUR WHERE ACTID IN (SELECT ACTID FROM DOSACTEUR WHERE ROLCODE = ''EMPRUNT''
	 AND DOSID IN (SELECT DOSID FROM DOSSIER WHERE DOSNUM = #PARAM1#) )'    , null
	FROM TEXOBJECT t WHERE CODEOBJECT='GET_LOCALPARTYIDENTIFIER'
	AND NOT EXISTS (SELECT 1 FROM TEXTREE tx WHERE tx.OBJID = t.OBJID AND tx.NODE='GET_LOCALPARTYIDENTIFIER');
	
	dbms_output.put_line('Script executé avec succes'); 
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
	dbms_output.put_line('Script executé avec succes'); 
	ROLLBACK;
END;
/    